GET https://shrouded-wildwood-33076-84272b329fbd.herokuapp.com/todos

###

POST https://shrouded-wildwood-33076-84272b329fbd.herokuapp.com/todo/new
Content-Type: application/json

{
	"text": "Pick up boat"
}

###

DELETE https://shrouded-wildwood-33076-84272b329fbd.herokuapp.com/todo/delete/64d397eb553ee54a800568f1

###

GET https://shrouded-wildwood-33076-84272b329fbd.herokuapp.com/todo/complete/64d397eb553ee54a800568f1

###

PUT https://shrouded-wildwood-33076-84272b329fbd.herokuapp.com/todo/update/64d397eb553ee54a800568f1
Content-Type: application/json

{
	"text": "Go Shopping for Milk"
}

GET https://shrouded-wildwood-33076-84272b329fbd.herokuapp.com/todo/complete/64d397eb553ee54a800568f1

###

PUT https://shrouded-wildwood-33076-84272b329fbd.herokuapp.com/todo/update/64d397eb553ee54a800568f1
Content-Type: application/json

{
	"text": "Go Shopping for Milk"
}
