GET http://localhost:3001/todos 

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
	"text": "Pick up boat"
}

###

DELETE http://localhost:3001/todo/delete/64d397eb553ee54a800568f1

###

GET http://localhost:3001/todo/complete/64d397eb553ee54a800568f1

###

PUT http://localhost:3001/todo/update/64d397eb553ee54a800568f1
Content-Type: application/json

{
	"text": "Go Shopping for Milk"
}


GET http://localhost:todo/complete/64d397eb553ee54a800568f1

###

PUT http://localhost:3001/todo/update/64d397eb553ee54a800568f1
Content-Type: application/json

{
	"text": "Go Shopping for Milk"
}